### ISSUE TITLE
Unable to add items to cart

### ISSUE THREAD

**Issue by mcneiljv** [AlexanderProd/nureineburg.de#1]
Hello there! I was just checking out your Gatsby Shopify site. I plan to use your theme for a project I'm working on. I was poking around the site and found that I am unable to add any shop items to my cart. I wanted to point out the issue just to make sure you know it's there.

Best,
Jamie McNeil

**Comment by AlexanderProd** [comment]
Hi, thanks for letting me know, this is because the shopify backend is currently offline.
